basePath: /
definitions:
  models.Reminder:
    properties:
      send_at:
        type: string
      status:
        default: pending
        type: string
      subject:
        type: string
      text:
        type: string
    required:
    - send_at
    - subject
    - text
    type: object
  models.RemindersWithTimeRange:
    properties:
      condition:
        type: string
      range_end:
        type: string
      range_start:
        type: string
      repeat_condition:
        enum:
        - year
        - month
        - week
        - day
        type: string
      subject:
        type: string
      text:
        type: string
    required:
    - range_end
    - range_start
    - repeat_condition
    - subject
    - text
    type: object
  models.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      registered_date:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  models.UserSignInRequest:
    properties:
      email:
        default: marisasha228@bk.ru
        type: string
      password:
        default: "123"
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@ttl-checker.com
    name: API Support
  description: API для отправки напоминаний на email
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TTL Email Scheduler API
  version: "1.0"
paths:
  /api/email-scheduler/reminder:
    get:
      consumes:
      - application/json
      operationId: get-reminders
      parameters:
      - description: Статус напоминания
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Просмотр напоминаний
      tags:
      - email-scheduler
  /api/email-scheduler/reminder/create:
    post:
      consumes:
      - application/json
      operationId: reminder-create
      parameters:
      - description: Информация для напоминания
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Reminder'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Создание нового напоминания
      tags:
      - email-scheduler
  /api/email-scheduler/reminder/create-range:
    post:
      consumes:
      - application/json
      operationId: reminder-create-range
      parameters:
      - description: Информация для создания диапазона напоминаний
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RemindersWithTimeRange'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Создание временного диапазона для напоминаний
      tags:
      - email-scheduler
  /api/email-scheduler/reminder/delete/{id}:
    delete:
      consumes:
      - application/json
      operationId: delete-reminder
      parameters:
      - description: Id reminder
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Удалить напоминание
      tags:
      - email-scheduler
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Проверка прав пользователя
      operationId: sign-in
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserSignInRequest'
      produces:
      - application/json
      responses: {}
      summary: Аутентификация пользователя
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создание нового пользователя
      operationId: sign-up
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses: {}
      summary: Регистрация пользователя
      tags:
      - auth
  /auth/verify-email/send:
    get:
      consumes:
      - application/json
      description: Отправка подтверждения почты пользователя
      operationId: token-send
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Отправка подтверждения почты пользователя
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: 'Введите: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
